git mv components/Comments.tsx components/Comments_temp.tsx
git mv components/Comments_temp.tsx components/Comments.tsx
git mv components/ui/button.tsx components/ui/button_temp.tsx
git mv components/ui/button_temp.tsx components/ui/button.tsx
git mv components/ui/card.tsx components/ui/card_temp.tsx
git mv components/ui/card_temp.tsx components/ui/card.tsx
git mv components/ui/badge.tsx components/ui/badge_temp.tsx
git mv components/ui/badge_temp.tsx components/ui/badge.tsx
git mv components/ui/avatar.tsx components/ui/avatar_temp.tsx
git mv components/ui/avatar_temp.tsx components/ui/avatar.tsx
